[package]
name = "autoclaim-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.6", features = ["derive"] }
ethers = "0.6.2"
serde_json = "1.0.79"
url = "2.2.2"
tokio = { version = "1.10.1", features = ["full"] }
hex = "0.4.3"
